#!/bin/sh

set -xe

if [ -z "$1" ]; then
    echo "Usage: $0 <prefix>"
    exit 1
fi

destdir=$1

builddir=`pwd`/build
sourcedir=`pwd`/source

for d in $builddir $destdir; do
    if [ -e $d ]; then
        rm -rf $d
    fi
done

extract() {
    path=$builddir/$1
    url=$2
    tarball=$sourcedir/`echo $url | sed -e 's/.*\///'`

    if [ ! -e $tarball ]; then
        curl -L -o $tarball $url
    fi

    mkdir $path
    tar xf $tarball -C $path --strip-components 1
}

if [ "`uname`" = "Linux" ]; then
    outputdir=/output
    outputfile=$outputdir/openssl-manylinux_$(uname -m).tar.bz2
elif [ "`uname`" = "Darwin" ]; then
    outputdir=`pwd`/output
    outputfile=$outputdir/openssl-macosx_$(uname -m).tar.bz2
else
    echo "Unknown platform"
    exit 1
fi


mkdir -p $outputdir
if [ ! -e $outputfile ]; then
    mkdir $builddir
    mkdir -p $sourcedir
    cd $builddir

    # build openssl
    extract openssl https://www.openssl.org/source/openssl-1.1.1f.tar.gz
    cd openssl
    ./config no-comp no-shared no-tests
    make

    # install headers and libraries
    mkdir $destdir
    mkdir $destdir/lib
    cp -R include $destdir
    cp libcrypto.a libssl.a $destdir/lib
    
    tar cjvf $outputfile -C $destdir include lib
fi
